global class BillingInfo {
    //Project ID
    webservice String projectId;
    //Credit card 
    WebService String ccAddress;//
    WebService String ccCity;
    WebService String ccPostalCode;
    WebService String ccState;
    WebService String ccCountry;
    WebService String ccBillingEmail;//
    //Billing info
    WebService String biCompanyName;//
    WebService String biAddress;//
    WebService String biCity;
    WebService String biPostalCode;
    WebService String biState;
    WebService String biCountry;
    WebService String biVATNumber;
    WebService String biAdditionalInfo;
}